name: Deploy / NuGet
run-name: Deploy / NuGet

on:
  workflow_call:
    inputs:
      changelog:
        default: ""
        description: A list of changes introduced in the new version of the package.
        required: false
        type: string
      environment-name:
        default: "NuGet (Stable)"
        description: The name of the environment that represents the deployment.
        required: false
        type: string
      project-path:
        default: ""
        description: The path of the project to build and pack.
        required: false
        type: string
      sanitize-version:
        default: true
        description: If true, sanitizes the inputted version by removing the `v` prefix and directories.
        required: false
        type: boolean
      version:
        default: ""
        description: The version of the package.
        required: false
        type: string
    secrets:
      NUGET-API-KEY:
        description: The API key to use to publish the package to NuGet.
        required: true

defaults:
  run:
    shell: bash

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_GENERATE_ASPNET_CERTIFICATE: 'false'
  DOTNET_NOLOGO: 'true'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'

jobs:
  deploy-nuget:
    environment:
      name: ${{ inputs.environment-name }}
      url: ${{ steps.build.outputs.PACKAGE-VERSION-URL }}

    runs-on: ubuntu-22.04
    timeout-minutes: 2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        id: setup-dotnet
        uses: actions/setup-dotnet@v3

      - name: Setup Environment
        env:
          PACKAGE_VERSION: ${{ inputs.version }}
        run: |
          # "Version" is the name of the MSBuild property,
          # so it's not in SCREAMING_CASE
          if ${{ inputs.sanitize-version }} ; then
            echo 'Version='"${PACKAGE_VERSION#**v}" >> "$GITHUB_ENV"
          fi



          msbuild_dir="$(dirname "$(which dotnet)")/sdk/${{ steps.setup-dotnet.outputs.dotnet-version }}/"
          msbuild_path="${msbuild_dir}MSBuild.dll"
          if [ ! -f "$msbuild_path" ]; then
            echo "Unable to find MSBuild.dll"
            exit 1
          fi

          echo 'MSBuild found at `'"$msbuild_path"'`.'

          importbefore__Microsoft_Common_targets="${msbuild_dir}Current/Microsoft.Common.targets/ImportBefore/"
          mkdir -p "$importbefore__Microsoft_Common_targets"

          targets_path="${importbefore__Microsoft_Common_targets}Deploy.NuGet.Common.targets"
          cat << 'EOF' > "$targets_path"
          <Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

          <!-- Outputs the package path for CI to use -->
        
          <!-- Expose variables for CI to use -->
          <Target Name="_ExposeCIVariables" AfterTargets="Pack" Condition="'$(EXPOSE_CI_VARIABLES)' == 'true'">
            <Error Text="%24%28GITHUB_OUTPUT%29 is undefined" Condition="'$(GITHUB_OUTPUT)' == ''" />
            <WriteLinesToFile File="$(GITHUB_OUTPUT)" Lines="PACKAGE-OUTPUT-PATH=$(PackageOutputAbsolutePath);PACKAGE-VERSION-URL=https://www.nuget.org/packages/$(PackageId)/$(PackageVersion)" />
          </Target>
        
          <!-- Prevent EXPOSE_CI_VARIABLES from propagating to project references -->
          <ItemGroup>
            <ProjectReference Update="@(ProjectReference)" UndefineProperties="%(ProjectReference.UndefineProperties);EXPOSE_CI_VARIABLES" />
          </ItemGroup>

          </Project>
          EOF

          echo 'Targets written to `'"$targets_path"'`.'

      - name: Build & Pack Project
        env:
          PackageReleaseNotes: ${{ inputs.changelog }}
          Version: ${{ env.Version || inputs.version }}
        id: build
        run: dotnet pack -warnaserror -c Release -p:EXPOSE_CI_VARIABLES=true ${{ inputs.project-path }}

      - name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          name: NuGet Packages
          path: |
            ${{ steps.build.outputs.PACKAGE-OUTPUT-PATH }}*.nupkg

      - name: Publish Package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET-API-KEY }}
        run: dotnet nuget push ${{ steps.build.outputs.PACKAGE-OUTPUT-PATH }}*.nupkg -k "$NUGET_API_KEY" -s "https://api.nuget.org/v3/index.json"
